### ISSUE TITLE
DefModelView Color Plot mirrored?

### ISSUE THREAD

**Issue by rudiwave** [Alpaca4d/OpenSeesGH#35]
The colors of the deformed mesh for the beams seem to be mirrored.

![Bildschirmfoto 2023-09-17 um 15 29 34](https://github.com/Alpaca4d/Alpaca4d/assets/66359415/3fdeb409-a1f8-41d5-a8ba-9ea24cf50430)

Here is the test file:
[eft_test.gh.zip](https://github.com/Alpaca4d/Alpaca4d/files/12642949/eft_test.gh.zip)

**Comment by Marco-Pellegrino** [comment]
fixed!
